// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdqrgefqvndgraoubuol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcXJnZWZxdm5kZ3Jhb3VidW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjI1MjUsImV4cCI6MjA2NjU5ODUyNX0.ZHhlGNAcYPYFfxEn6W-NlSX1di5aYqs8wYibY8sXsNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);